<?php

namespace RecepiesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecepieRepository extends EntityRepository
{
    public function findAllOrderedByName(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM RecepiesBundle:Recepie r ORDER BY r.title ASC'
            )
            ->getResult();
        /* Method can be used inside a Controller as follows
        $em = $this->getDoctrine()->getManager();
        $products = $em->getRepository('AppBundle:Product')
            ->findAllOrderedByName();
        */
    }

}
